version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
    -  "27017:27017"
    links:
    - mongo
  mongo:
     image: dockerfile/ubuntu
     volumes_from:
     - data
     ports:
     -   "127.0.0.1:27017:27017"
     container_name: "db_mongodb"


  data:
    image: dockerfile/ubuntu
    volumes:
      - /var/lib/mongo
      - ./dc-mongo-setup:/setup
    command: "true"
    container_name: "db_mongodb_data"
